#pragma once

#define DINPUT_ESCAPE          0x01
#define DINPUT_1               0x02
#define DINPUT_2               0x03
#define DINPUT_3               0x04
#define DINPUT_4               0x05
#define DINPUT_5               0x06
#define DINPUT_6               0x07
#define DINPUT_7               0x08
#define DINPUT_8               0x09
#define DINPUT_9               0x0A
#define DINPUT_0               0x0B
#define DINPUT_MINUS           0x0C
#define DINPUT_EQUALS          0x0D
#define DINPUT_BACK            0x0E
#define DINPUT_TAB             0x0F
#define DINPUT_Q               0x10
#define DINPUT_W               0x11
#define DINPUT_E               0x12
#define DINPUT_R               0x13
#define DINPUT_T               0x14
#define DINPUT_Y               0x15
#define DINPUT_U               0x16
#define DINPUT_I               0x17
#define DINPUT_O               0x18
#define DINPUT_P               0x19
#define DINPUT_LBRACKET        0x1A
#define DINPUT_RBRACKET        0x1B
#define DINPUT_RETURN          0x1C
#define DINPUT_LCONTROL        0x1D
#define DINPUT_A               0x1E
#define DINPUT_S               0x1F
#define DINPUT_D               0x20
#define DINPUT_F               0x21
#define DINPUT_G               0x22
#define DINPUT_H               0x23
#define DINPUT_J               0x24
#define DINPUT_K               0x25
#define DINPUT_L               0x26
#define DINPUT_SEMICOLON       0x27
#define DINPUT_APOSTROPHE      0x28
#define DINPUT_GRAVE           0x29
#define DINPUT_LSHIFT          0x2A
#define DINPUT_BACKSLASH       0x2B
#define DINPUT_Z               0x2C
#define DINPUT_X               0x2D
#define DINPUT_C               0x2E
#define DINPUT_V               0x2F
#define DINPUT_B               0x30
#define DINPUT_N               0x31
#define DINPUT_M               0x32
#define DINPUT_COMMA           0x33
#define DINPUT_PERIOD          0x34
#define DINPUT_SLASH           0x35
#define DINPUT_RSHIFT          0x36
#define DINPUT_MULTIPLY        0x37
#define DINPUT_LMENU           0x38
#define DINPUT_SPACE           0x39
#define DINPUT_CAPITAL         0x3A
#define DINPUT_F1              0x3B
#define DINPUT_F2              0x3C
#define DINPUT_F3              0x3D
#define DINPUT_F4              0x3E
#define DINPUT_F5              0x3F
#define DINPUT_F6              0x40
#define DINPUT_F7              0x41
#define DINPUT_F8              0x42
#define DINPUT_F9              0x43
#define DINPUT_F10             0x44
#define DINPUT_NUMLOCK         0x45
#define DINPUT_SCROLL          0x46
#define DINPUT_NUMPAD7         0x47
#define DINPUT_NUMPAD8         0x48
#define DINPUT_NUMPAD9         0x49
#define DINPUT_SUBTRACT        0x4A
#define DINPUT_NUMPAD4         0x4B
#define DINPUT_NUMPAD5         0x4C
#define DINPUT_NUMPAD6         0x4D
#define DINPUT_ADD             0x4E
#define DINPUT_NUMPAD1         0x4F
#define DINPUT_NUMPAD2         0x50
#define DINPUT_NUMPAD3         0x51
#define DINPUT_NUMPAD0         0x52
#define DINPUT_DECIMAL         0x53
#define DINPUT_OEM_102         0x56    
#define DINPUT_F11             0x57
#define DINPUT_F12             0x58
#define DINPUT_F13             0x64
#define DINPUT_F14             0x65    
#define DINPUT_F15             0x66    
#define DINPUT_KANA            0x70    
#define DINPUT_ABNT_C1         0x73    
#define DINPUT_CONVERT         0x79    
#define DINPUT_NOCONVERT       0x7B    
#define DINPUT_YEN             0x7D    
#define DINPUT_ABNT_C2         0x7E    
#define DINPUT_NUMPADEQUALS    0x8D   
#define DINPUT_PREVTRACK       0x90    
#define DINPUT_AT              0x91
#define DINPUT_COLON           0x92
#define DINPUT_UNDERLINE       0x93
#define DINPUT_KANJI           0x94
#define DINPUT_STOP            0x95
#define DINPUT_AX              0x96
#define DINPUT_UNLABELED       0x97
#define DINPUT_NEXTTRACK       0x99
#define DINPUT_NUMPADENTER     0x9C
#define DINPUT_RCONTROL        0x9D
#define DINPUT_MUTE            0xA0
#define DINPUT_CALCULATOR      0xA1
#define DINPUT_PLAYPAUSE       0xA2
#define DINPUT_MEDIASTOP       0xA4
#define DINPUT_VOLUMEDOWN      0xAE
#define DINPUT_VOLUMEUP        0xB0
#define DINPUT_WEBHOME         0xB2
#define DINPUT_NUMPADCOMMA     0xB3
#define DINPUT_DIVIDE          0xB5
#define DINPUT_SYSRQ           0xB7
#define DINPUT_RMENU           0xB8
#define DINPUT_PAUSE           0xC5
#define DINPUT_HOME            0xC7
#define DINPUT_UP              0xC8
#define DINPUT_PRIOR           0xC9
#define DINPUT_LEFT            0xCB
#define DINPUT_RIGHT           0xCD
#define DINPUT_END             0xCF
#define DINPUT_DOWN            0xD0
#define DINPUT_NEXT            0xD1
#define DINPUT_INSERT          0xD2
#define DINPUT_DELETE          0xD3
#define DINPUT_LWIN            0xDB
#define DINPUT_RWIN            0xDC
#define DINPUT_APPS            0xDD
#define DINPUT_POWER           0xDE
#define DINPUT_SLEEP           0xDF
#define DINPUT_WAKE            0xE3
#define DINPUT_WEBSEARCH       0xE5
#define DINPUT_WEBFAVORITES    0xE6
#define DINPUT_WEBREFRESH      0xE7
#define DINPUT_WEBSTOP         0xE8
#define DINPUT_WEBFORWARD      0xE9
#define DINPUT_WEBBACK         0xEA
#define DINPUT_MYCOMPUTER      0xEB
#define DINPUT_MAIL            0xEC
#define DINPUT_MEDIASELECT     0xED

#define DINPUT_BACKSPACE       DINPUT_BACK
#define DINPUT_NUMPADSTAR      DINPUT_MULTIPLY
#define DINPUT_LALT            DINPUT_LMENU
#define DINPUT_CAPSLOCK        DINPUT_CAPITAL
#define DINPUT_NUMPADMINUS     DINPUT_SUBTRACT
#define DINPUT_NUMPADPLUS      DINPUT_ADD
#define DINPUT_NUMPADPERIOD    DINPUT_DECIMAL
#define DINPUT_NUMPADSLASH     DINPUT_DIVIDE
#define DINPUT_RALT            DINPUT_RMENU
#define DINPUT_UPARROW         DINPUT_UP
#define DINPUT_PGUP            DINPUT_PRIOR
#define DINPUT_LEFTARROW       DINPUT_LEFT
#define DINPUT_RIGHTARROW      DINPUT_RIGHT
#define DINPUT_DOWNARROW       DINPUT_DOWN
#define DINPUT_PGDN            DINPUT_NEXT

#define DINPUT_CIRCUMFLEX      DINPUT_PREVTRACK
