#pragma once

// win32
#define ERRLVL_WIN32_GET_MODULE_HANDLE				100
#define ERRLVL_WIN32_REGISTER_WINDOW_CLASS			102
#define ERRLVL_WIN32_ADJUST_WINDOW_RECT				103
#define ERRLVL_WIN32_CREATE_WINDOW					104
#define ERRLVL_WIN32_SHOW_WINDOW					105
#define ERRLVL_WIN32_UPDATE_WINDOW					106
#define ERRLVL_WIN32_SET_FOREGROUND_WINDOW			107
#define ERRLVL_WIN32_SET_PROP_WINDOW				108
#define ERRLVL_WIN32_DESTROY_WINDOW					109
#define ERRLVL_WIN32_UNREGISTER_WINDOW_CLASS		110
#define ERRLVL_WIN32_TRANSLATE_MESSAGE				111
#define ERRLVL_WIN32_DISPATCH_MESSAGE				112
#define ERRLVL_WIN32_CREATE_THREAD					113
#define ERRLVL_WIN32_GENERATE_GUID					114

// d3d11
#define ERRLVL_D3D11_NULL_WINDOW					200
#define ERRLVL_D3D11_CREATE_DEVICE_AND_SWAPCHAIN	201
#define ERRLVL_D3D11_SWAPCHAIN_GET_BUFFER			202
#define ERRLVL_D3D11_DEVICE_CREATE_RTV				203
#define ERRLVL_D3D11_CREATE_TEXTURE2D				204
#define ERRLVL_D3D11_CREATE_DEPTH_STENCIL_VIEW		205
#define ERRLVL_D3D11_CREATE_RASTERIZER_STATE		206
#define ERRLVL_D3D11_CREATE_SAMPLER_STATE			207
#define ERRLVL_D3D11_PRESENT						208
#define ERRLVL_D3D11_CREATE_BUFFER					209
#define ERRLVL_D3D11_CREATE_SHADER_RESOURCE_VIEW	210
#define ERRLVL_D3D11_CREATE_VERTEX_SHADER			211
#define ERRLVL_D3D11_CREATE_PIXEL_SHADER			212
#define ERRLVL_D3D11_CREATE_SPRITEFONT				213
#define ERRLVL_D3D11_CREATE_INPUT_LAYOUT			214
#define ERRLVL_D3D11_RESIZE_BUFFERS					215
#define ERRLVL_D3D11_COMPILE_SHADER_FROM_FILE		216

// openssl
#define ERRLVL_OPENSSL_MEMORY_ALLOCATE				300
#define ERRLVL_OPENSSL_SET_WORD						301
#define ERRLVL_OPENSSL_GENERATE_KEY					302
#define ERRLVL_OPENSSL_WRITE_KEY					303
#define ERRLVL_OPENSSL_READ							304

// dinput
#define ERRLVL_DINPUT_NULL_WINDOW					401
#define ERRLVL_DINPUT_CREATE_DEVICE					402
#define ERRLVL_DINPUT_DEVICE_SET_DATA_FORMAT		403
#define ERRLVL_DINPUT_DEVICE_SET_COOP_LEVEL			404
#define ERRLVL_DINPUT_DEVICE_ACQUIRE				405
#define ERRLVL_DINPUT_ENUM_KEYBOARD_DEVICES			406
#define ERRLVL_DINPUT_ENUM_MOUSE_DEVICES			407
#define ERRLVL_DINPUT_ENUM_GAME_DEVICES				408
#define ERRLVL_DINPUT_DEVICE_DISCONNECTED			409

// dx
#define ERRLVL_DX_MEMORY_ALLOCATE					500
#define ERRLVL_DX_CREATE_SHADER_RESOURCE_VIEW		501
#define ERRLVL_DX_LOAD_FROM_DDS_FILE				502
#define ERRLVL_DX_LOAD_FROM_TGA_FILE				503
#define ERRLVL_DX_LOAD_FROM_HDR_FILE				504
#define ERRLVL_DX_LOAD_FROM_WIC_FILE				505

// btphysics
#define ERRLVL_BTPHYS_MEMORY_ALLOCATE				600
#define ERRLVL_BTPHYS_NOT_SIMULATED					601
#define ERRLVL_BTPHYS_NULL_MESH						602
#define ERRLVL_BTPHYS_EMPTY_VERTICES_CONTAINER		603
#define ERRLVL_BTPHYS_EMPTY_INDICES_CONTAINER		604
#define ERRLVL_BTPHYS_NULL_PHYSICS_WORLD			605
#define ERRLVL_BTPHYS_NONE_COLLISION_SHAPE_TYPE		606
#define ERRLVL_BTPHYS_UNKNOWN_COLLISION_SHAPE_TYPE	607
#define ERRLVL_BTPHYS_NULL_VERTICES_PTR				608
#define ERRLVL_BTPHYS_NULL_INDICES_PTR				607

// winsock2
#define ERRLVL_WS2_CREATE_SOCKET					700
#define ERRLVL_WS2_CONVERT_IPADDR_TO_NET			701
#define ERRLVL_WS2_CONVERT_IPADDR_TO_TXT			702
#define ERRLVL_WS2_BIND_ADDR						703
#define ERRLVL_WS2_LISTEN							704
#define ERRLVL_WS2_ACCEPT							705
#define ERRLVL_WS2_RECV								706
#define ERRLVL_WS2_SEND								707
#define ERRLVL_WS2_CONNECT							708
#define ERRLVL_WS2_SHUTDOWN_SOCKET					709
#define ERRLVL_WS2_CLOSE_SOCKET						710

// io
#define ERRLVL_IO_CREATE_IOCP						800

// steam api
#define ERRLVL_STEAM_API_INIT						900

// gameframework
#define ERRLVL_GF_MEMORY_ALLOCATE					100000
#define ERRLVL_GF_GAME_LOGIC_NOT_DEFINED			100001
#define ERRLVL_GF_NULL_MESH							100002
#define ERRLVL_GF_NOT_VALID_VERTICES_BUFFER			100003
#define ERRLVL_GF_NOT_VALID_INDICES_BUFFER			100004
